---
title: "Homework Assignment 2"
author: "Claes Kock, Yuchong Wu, Mayara Latrech"
Date: "10/12/2019"
header-includes:
   - \usepackage{array}
   - \usepackage{float}
output:
  pdf_document:
    number_sections: yes
---

# Caution: Never copy the whole thing into the latest version from your own workspace

# Example for making table:

```{r eval=FALSE}
table = data.frame(column1 = c(1, 2, "text"), 
                   column2 = c(4, 5, 6))

# Then for PDF:
kable(table, caption = "title here", digits = 2)

# For presentation:
datatable(table)
```

# Reminders:

1. Titles for all the plots and tables

***

\newpage

\tableofcontents

\newpage

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', echo = FALSE)
library(knitr)
library(ggplot2)
library(tidyverse)
library(semPlot)
library(lavaan)
```

```{r}
load("HolzingerSwineford1939.RData")
dat = as.data.frame(df)
dat
dat_t = dat 
dat_t$school = as.numeric(dat_t$school)
```




### Model 3




```{r}
model <- '
   # latent variables
     geo_abi =~ x1 + x2 + x3
     lan_abi =~ x4 + x5 + x6 
     alg_abi =~ x7 + x8 + x9
   # regressions
     geo_abi ~ ageyr + grade + sex
     lan_abi ~ ageyr + grade + sex
     alg_abi ~ ageyr + grade + sex
   # residual covariances
'


fit = cfa(model, data=dat_t,group = "school")




#summary(fit, fit.measures = TRUE)
#devAskNewPage(ask = FALSE)
#semPaths(fit)

Eval4 = fitMeasures(fit, c("aic","bic" ,"cfi","rmsea","srmr"))

```

### Models evaluation



